#!/bin/bash
# -*- coding: utf-8 -*-
"""
测试脚本
"""

echo "====================================="
echo "OpenClaw 统一量化交易平台 v5.0 - 网页测试"
echo "======================================"
echo ""
echo ""
echo "测试登录功能..."
echo "curl -X POST http://localhost:5000/api/auth/login -H \"Content-Type: application/json\" -d \"{\\\"username\\\": \"admin\\\",\\\"password\\\": \"admin123\\\"}'"
echo ""
echo "预期结果:"
echo "  {\"success\\\": True, \\\"message\\\": \\\"登录成功\\\", \\\"token\\\": token, \\\"user\\\": user}"
echo ""
echo ""
echo "测试实时分析功能..."
echo "curl -s http://localhost:5000/api/analysis/realtime/600000 | jq -r '.success' && echo "" "
echo "预期结果:"
echo "  {\\\"success\\\": True, \\\"message\\\": \\\"实时分析完成\\\", \\\"data\\\": \"实时数据\\\"}"
echo ""
echo ""
echo "测试筹码分布分析..."
echo "curl -s http://localhost:5000/api/analysis/chip/600000 | jq -r '.success' && echo "
echo "预期结果:"
echo " {\\\"success\\\": True, \\\"message\\\": \\\"筹码分布完成\\\", \\\"data\\\": \\\"筹码分布数据\\\"}"
echo ""
echo ""
echo "测试市场综合分析..."
echo "curl -s http://localhost:5000/api/analysis/market | jq -r '.success' && echo "
echo "预期结果:"
echo " {\\\"success\\\": True, \\\"message\\\": \\\"市场综合分析完成\\\", \\\"data\\\": \\\"市场综合分析\\\"}"
echo ""
echo ""
echo "测试导出功能..."
echo "curl -s http://localhost:5000/api/export/pdf | jq -r '.success' && echo "
echo "预期结果:"
echo " {\\\"success\\\": True, \\\"message\\\": \\\"导出PDF完成\\\", \\\"data\\\": \\\"导出PDF完成\\\"}"
echo ""
echo ""
echo "测试飞书文档导出..."
echo "curl -s http://localhost:5000/api/export/feishu | jq -r '.success' && echo "
echo "预期结果:"
echo " {\\\"success\\\": True, \\\"message\\\": \\\"飞书文档导出完成\\\", \\\"content\\\": \\\"飞书文档导出完成\\\""
echo ""
echo ""
echo "=== ✅ 所有测试完成 ==="
echo ""
